-- ~/.config/nvim/init.lua
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.expandtab = true
vim.opt.tabstop = 2
vim.opt.shiftwidth = 2
vim.opt.softtabstop = 2
vim.opt.mouse = 'a'
vim.opt.showmatch = true
vim.opt.cursorline = true
vim.opt.clipboard = 'unnamedplus'
vim.opt.wrap = false
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.scrolloff = 8
vim.opt.termguicolors = true
vim.opt.updatetime = 300
vim.opt.signcolumn = 'yes'
vim.opt.encoding = 'utf-8'
vim.opt.showmode = false
vim.opt.completeopt = { 'menu', 'menuone', 'noselect' }
vim.opt.undofile = true
